### ISSUE TITLE
Does it help if Wingstop and BWW get classified as same subtype?

### ISSUE THREAD

**Issue by coleschram** [ChaseCallahan37/541_group_proj#17]
https://github.com/ChaseCallahan37/541_group_proj/blame/c114be4da3c917814fbbec4e6e2345607fb896b9/main.py#L458

Does it help anything if they are same subtype of chicken_wing_places? Can they be the same subtype and not be same top level type?

**Comment by ChaseCallahan37** [comment]
I believe so, It might make sense to place them as the same type tbh. That was generated by chat

**Comment by coleschram** [comment]
resolved by #22
