### ISSUE TITLE
Realtor data: Is it used?

### ISSUE THREAD

**Issue by coleschram** [ChaseCallahan37/541_group_proj#18]
https://github.com/ChaseCallahan37/541_group_proj/blob/c114be4da3c917814fbbec4e6e2345607fb896b9/main.py#L503

Do we ultimately use Realtor Data for Zip code calculations? Or we can clean up and remove all of this?

**Comment by ChaseCallahan37** [comment]
> https://github.com/ChaseCallahan37/541_group_proj/blob/c114be4da3c917814fbbec4e6e2345607fb896b9/main.py#L503
> 
> Do we ultimately use Realtor Data for Zip code calculations? Or we can clean up and remove all of this?

We can remove this!

**Comment by coleschram** [comment]
#21
